"""Diversity matrix. Fixed seeds guarantee different people and make evals deterministic.

The LLM fills in realistic detail around these facts; it must not contradict them.
"""
from __future__ import annotations

from .models import Seed

SEEDS: list[Seed] = [
    Seed(id="c01", name="Lucía Fernández Ortega", role="Senior Data Scientist", level="senior", years=8,
         location="Madrid, Spain", languages="Spanish (native), English (C1), French (B1)",
         stack="Python, pandas, scikit-learn, SQL, Airflow, A/B testing",
         education="MSc Statistics, Universidad Complutense de Madrid",
         style="European CV, concise, metrics-heavy", template="classic",
         photo="woman, early 30s, Spanish; plain light-grey studio backdrop, soft even light, dark blazer"),
    Seed(id="c02", name="Priya Raman", role="Staff Machine Learning Engineer", level="staff", years=11,
         location="London, United Kingdom", languages="English (fluent), Hindi (native), Tamil (native)",
         stack="Python, PyTorch, Kubernetes, MLOps, feature stores, LLM fine-tuning, recommender systems",
         education="PhD Computer Science (ML), IIT Madras",
         style="dense senior CV with publications and a projects section", template="modern",
         photo="woman, late 30s, South Indian; standing by a window in a bright modern office, daylight from the side, smart casual"),
    Seed(id="c03", name="Tomasz Nowak", role="Java Backend Developer", level="mid", years=5,
         location="Kraków, Poland", languages="Polish (native), English (B2), German (A2)",
         stack="Java 17, Spring Boot, Kafka, PostgreSQL, Docker",
         education="BSc Computer Science, AGH University of Kraków",
         style="plain, slightly terse bullets", template="compact",
         photo="man, late 20s, Polish; plain white wall, slightly flat phone-camera look, crew-neck sweater"),
    Seed(id="c04", name="Anna Petrosyan", role="Junior Frontend Developer", level="junior", years=1,
         location="Yerevan, Armenia", languages="Armenian (native), Russian (fluent), English (B2)",
         stack="React, TypeScript, HTML/CSS, Tailwind, Git",
         education="Bootcamp certificate + BA Linguistics, Yerevan State University",
         style="one page, career switcher, includes pet projects", template="modern",
         photo="woman, mid 20s, Armenian; outdoors on a city street with soft blurred buildings, overcast light, casual jacket"),
    Seed(id="c05", name="Mateo Rojas Quintero", role="Site Reliability Engineer", level="senior", years=7,
         location="Bogotá, Colombia (remote)", languages="Spanish (native), English (C1), Portuguese (B1)",
         stack="AWS, Terraform, Kubernetes, Go, Prometheus, incident management",
         education="Ingeniería de Sistemas, Universidad de los Andes",
         style="remote-first, on-call and reliability metrics", template="classic",
         photo="man, early 30s, Colombian; home office with a bookshelf behind, warm lamp light, casual shirt"),
    Seed(id="c06", name="Chen Wei", role="iOS Tech Lead", level="lead", years=10,
         location="Singapore", languages="Mandarin (native), English (fluent)",
         stack="Swift, SwiftUI, Objective-C, CI for mobile, team leadership",
         education="BEng Software Engineering, Fudan University",
         style="product-impact bullets, app store metrics", template="compact",
         photo="man, mid 30s, Chinese; dark charcoal studio backdrop, crisp studio lighting, open-collar shirt"),
    Seed(id="c07", name="Fatima Zahra El Amrani", role="Senior Product Designer", level="senior", years=6,
         location="Paris, France", languages="Arabic (native), French (native), English (C1)",
         stack="Figma, user research, design systems, prototyping (no programming)",
         education="Master Design d'interaction, ENSCI Les Ateliers",
         style="designer CV, portfolio link, case studies", template="modern",
         photo="woman, around 30, Moroccan; exposed brick wall in a design studio, natural light, stylish minimal top"),
    Seed(id="c08", name="Johannes Becker", role="Senior Embedded Software Engineer", level="senior", years=14,
         location="Munich, Germany", languages="German (native), English (C1)",
         stack="C, C++, RTOS, AUTOSAR, CAN bus, automotive safety (ISO 26262)",
         education="Dipl.-Ing. Electrical Engineering, TU München",
         style="German Lebenslauf style, chronological, formal", template="classic",
         photo="man, early 40s, German; classic formal Bewerbungsfoto, light-blue studio gradient, suit and tie"),
    Seed(id="c09", name="Olumide Adeyemi", role="Data Engineer", level="mid", years=4,
         location="Lagos, Nigeria", languages="English (native), Yoruba (native)",
         stack="Python, Apache Spark, dbt, BigQuery, GCP, Airflow",
         education="BSc Computer Engineering, University of Lagos",
         style="fintech data pipelines, cost savings", template="compact",
         photo="man, late 20s, Nigerian; outdoors with green trees softly blurred, warm afternoon sun, polo shirt"),
    Seed(id="c10", name="Sarah Mitchell", role="Engineering Manager", level="manager", years=15,
         location="Austin, Texas, USA", languages="English (native), Spanish (A2, basic)",
         stack="Node.js, TypeScript, hiring, org design, delivery management",
         education="BS Computer Science, University of Texas at Austin",
         style="US resume, no photo tradition but include one, leadership outcomes", template="classic",
         photo="woman, early 40s, American; corporate headshot against a mid-grey backdrop, confident smile, blouse and blazer"),
    Seed(id="c11", name="Elena Popescu", role="QA Automation Engineer", level="mid", years=6,
         location="Bucharest, Romania", languages="Romanian (native), English (C1), Italian (B2)",
         stack="Python, Playwright, Selenium, pytest, CI/CD, API testing",
         education="BSc Automatic Control and Computers, Politehnica University of Bucharest",
         style="testing strategy, bug metrics", template="modern",
         photo="woman, early 30s, Romanian; cozy cafe interior with bokeh lights behind, indoor warm light, knit sweater"),
    Seed(id="c12", name="Daniel Kim", role="Junior ML Researcher", level="junior", years=1,
         location="Toronto, Canada", languages="English (native), Korean (fluent)",
         stack="Python, PyTorch, Hugging Face Transformers, NLP evaluation",
         education="MSc Computer Science, University of Toronto (2025)",
         style="academic-leaning, one workshop paper, TA experience", template="compact",
         photo="man, mid 20s, Korean-Canadian; university campus hallway, slightly candid framing, hoodie"),
]
SEEDS_BY_ID: dict[str, Seed] = {seed.id: seed for seed in SEEDS}
